# Generated by Django 3.2 on 2024-12-07 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mpesaRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(max_length=50)),
                ('checkout_id', models.CharField(max_length=50)),
                ('res_code', models.IntegerField()),
                ('res_text', models.CharField(max_length=150)),
                ('msg', models.CharField(max_length=150)),
                ('ref', models.CharField(max_length=150)),
                ('trans_dec', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('trans_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MpesaPayments',
            fields=[
                ('receipt', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('merchant_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('checkout_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('res_code', models.IntegerField(blank=True, default=0, null=True)),
                ('res_text', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=13, null=True)),
                ('trans_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
